export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const FETCH_CART = 'FETCH_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REDUCE_FROM_CART = 'REDUCE_FROM_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PAST_ORDERS = 'FETCH_PAST_ORDERS';
export const CART_LOADED = 'CART_LOADED';
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_PRODUCTS_BY_CATEGORY = 'FETCH_PRODUCTS_BY_CATEGORY';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';

