SET SQL_SAFE_UPDATES = 0;
USE farm_necessities;
delete from product_category;
drop table product_category;
delete from category;
drop table category;
delete from order_detail;
drop table order_detail;
delete from order_history;
drop table order_history;
delete from address;
drop table address;
delete from payment_detail;
drop table payment_detail;
delete from rating;
drop table rating;
delete from cart;
drop table cart;
delete from product;
drop table product;
delete from user;
drop table user;